"""
Kōan -- Plan runner.

Generates structured implementation plans and posts them as GitHub issues
or comments. Extracted from the /plan skill handler so it can run as a
queued mission via run.py instead of inline in the bridge process.

Issue-centric workflow:
  - New idea: search for existing plan issue first, update if found, create if not
  - Existing issue URL: read all comments, produce updated plan, post as comment
  - Always reuse existing issues to keep the conversation in one place

CLI:
    python3 -m app.plan_runner --project-path <path> --idea "Add dark mode"
    python3 -m app.plan_runner --project-path <path> --issue-url <url>
"""

import re
import sys
from pathlib import Path
from typing import Optional, Tuple

from app.issue_tracker import (
    add_comment,
    create_issue,
    fetch_issue,
    find_existing_plan_issue,
    project_name_for_path,
    resolve_issue_ref,
    tracker_is_configured,
    tracker_supports_labels,
)
from app.prompts import load_prompt_or_skill

# Label used to tag plan issues for searchability
_PLAN_LABEL = "plan"


def run_plan(
    project_path: str,
    idea: Optional[str] = None,
    issue_url: Optional[str] = None,
    notify_fn=None,
    skill_dir: Optional[Path] = None,
    context: Optional[str] = None,
) -> Tuple[bool, str]:
    """Execute the plan pipeline.

    Either generates a new plan (idea mode) or iterates on an existing
    issue (issue_url mode). Exactly one of idea or issue_url must be set.

    Args:
        context: Optional additional user context (e.g. "Focus on phase 2").
                 Appended to the issue context or passed to plan generation.

    Returns:
        (success, summary) tuple.
    """
    if notify_fn is None:
        from app.notify import send_telegram
        notify_fn = send_telegram

    # Heartbeat so the liveness watchdog in run.py knows we're alive
    # before Claude CLI starts streaming.
    print("[plan] Starting plan runner", flush=True)

    if issue_url:
        return _run_issue_plan(
            project_path, issue_url, notify_fn, skill_dir, context=context,
        )
    elif idea:
        return _run_new_plan(
            project_path, idea, notify_fn, skill_dir, context=context,
        )
    else:
        return False, "No idea or issue URL provided."


def _run_new_plan(
    project_path: str,
    idea: str,
    notify_fn,
    skill_dir: Optional[Path],
    context: Optional[str] = None,
) -> Tuple[bool, str]:
    """Generate a plan for a new idea, reusing an existing issue if found."""
    notify_fn(f"\U0001f9e0 Planning: {idea[:100]}{'...' if len(idea) > 100 else ''}")
    print(f"[plan] New plan for: {idea[:80]}", flush=True)

    project_name = project_name_for_path(project_path)

    existing = find_existing_plan_issue(project_name, project_path, idea)
    if existing:
        notify_fn(
            f"\U0001f504 Found existing {existing.provider} issue "
            f"{existing.label} — iterating"
        )
        return _run_issue_plan(
            project_path, existing.url, notify_fn, skill_dir, context=context,
        )

    print("[plan] Invoking Claude for plan generation", flush=True)
    try:
        plan = _generate_plan(
            project_path, idea, context=context or "", skill_dir=skill_dir,
        )
    except Exception as e:
        return False, f"Plan generation failed: {str(e)[:300]}"

    if not plan:
        return False, "Claude returned an empty plan."

    title = _extract_title(plan)
    plan_body = _strip_title_line(plan)
    issue_body = f"{plan_body}\n\n---\n*Generated by Kōan /plan*"

    if not tracker_is_configured(project_name, project_path):
        notify_fn(f"✅ Plan generated inline:\n\n{plan[:3000]}")
        return True, "Plan generated inline (no issue tracker configured)."

    labels = [_PLAN_LABEL] if tracker_supports_labels(project_name, project_path) else None
    try:
        result_url = create_issue(
            project_name, project_path, title, issue_body, labels=labels,
        )
    except (RuntimeError, OSError):
        # GitHub labels may not exist; Jira ignores them. Retry without labels.
        try:
            result_url = create_issue(project_name, project_path, title, issue_body)
        except (RuntimeError, OSError) as e2:
            notify_fn(
                f"⚠️ Plan ready but tracker issue creation failed "
                f"({e2}):\n\n{plan[:3000]}"
            )
            return True, f"Plan generated but issue creation failed: {e2}"

    notify_fn(f"✅ Plan created: {result_url}")
    return True, f"Plan created: {result_url}"


def _run_issue_plan(
    project_path: str,
    issue_url: str,
    notify_fn,
    skill_dir: Optional[Path],
    context: Optional[str] = None,
) -> Tuple[bool, str]:
    """Read an existing issue/PR + comments, generate updated plan, post comment."""
    project_name = project_name_for_path(project_path)

    # Resolve the reference first (no network) for a useful heartbeat and to
    # validate the URL; the tracker then handles fetch/comment generically.
    try:
        ref = resolve_issue_ref(
            issue_url, project_name=project_name, project_path=project_path,
        )
    except Exception as e:
        return False, f"Failed to fetch issue: {str(e)[:300]}"

    notify_fn(f"\U0001f4d6 Reading {ref.provider} issue {ref.label}...")
    print(f"[plan] Fetching tracker issue {issue_url}", flush=True)

    try:
        content = fetch_issue(
            issue_url, project_name=project_name, project_path=project_path,
        )
    except Exception as e:
        return False, f"Failed to fetch issue: {str(e)[:300]}"

    title = content.title
    body = content.body
    comments_text = _format_comments(content.comments)
    label = content.ref.label

    print("[plan] Issue fetched, building prompt", flush=True)
    # Build full issue context for the iteration prompt
    context_parts = [f"## Original Issue {label}: {title}\n\n{body}"]
    if comments_text:
        context_parts.append(f"\n\n## Discussion Comments\n\n{comments_text}")
    else:
        context_parts.append("\n\n*No comments yet on this issue.*")
    if context:
        context_parts.append(f"\n\n## User Instructions\n\n{context}")
    issue_context = "\n".join(context_parts)

    print("[plan] Invoking Claude for plan generation", flush=True)
    try:
        plan = _generate_iteration_plan(
            project_path, issue_context, skill_dir=skill_dir
        )
    except Exception as e:
        return False, f"Plan generation failed: {str(e)[:300]}"

    if not plan:
        return False, "Claude returned an empty plan."

    iteration_title = _extract_title(plan)
    plan_body = _strip_title_line(plan)
    comment_body = (
        f"## {iteration_title}\n\n{plan_body}\n\n---\n"
        f"*Generated by Kōan /plan — iteration on existing issue*"
    )

    try:
        add_comment(
            issue_url, comment_body,
            project_name=project_name,
            project_path=project_path,
        )
    except Exception as e:
        notify_fn(f"Plan ready but comment failed ({e}):\n\n{plan[:3000]}")
        return True, f"Plan generated but comment failed: {e}"

    if title:
        label = f"{label} ({title[:60]})"
    notify_fn(f"✅ Plan posted as comment on {label}: {issue_url}")
    return True, f"Plan posted on {label}: {issue_url}"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

# Minimum phase count and line count below which review is skipped.
# Single-phase plans under this line threshold are considered trivially simple.
_REVIEW_SKIP_PHASES = 2   # skip if fewer than this many phases
_REVIEW_SKIP_LINES = 20   # skip if plan body is shorter than this


def is_simple_plan(plan_text: str) -> bool:
    """Return True if the plan is trivially simple and doesn't need review.

    Skips review for single-phase plans with fewer than _REVIEW_SKIP_LINES
    lines — e.g. "rename function X to Y" doesn't need a subagent review.
    """
    phase_count = len(re.findall(r'^#{1,4}\s*Phase\b', plan_text, re.MULTILINE | re.IGNORECASE))
    if phase_count >= _REVIEW_SKIP_PHASES:
        return False
    line_count = len([l for l in plan_text.splitlines() if l.strip()])
    return line_count < _REVIEW_SKIP_LINES


def review_plan(plan_text: str, project_path: str, skill_dir) -> Tuple[bool, str]:
    """Run a lightweight subagent to review plan quality.

    Args:
        plan_text: The generated plan text to review.
        project_path: Project directory (for run_command cwd).
        skill_dir: Skill directory for loading the review prompt.

    Returns:
        (approved, issues) tuple:
          - approved=True, issues="" when APPROVED
          - approved=False, issues=<bullet list> when ISSUES_FOUND
          - approved=True, issues="" on reviewer error (fail open)
    """
    from app.cli_provider import run_command

    try:
        prompt = load_prompt_or_skill(skill_dir, "plan-review", PLAN=plan_text)
    except Exception as e:
        print(f"[plan_runner] Review prompt load failed: {e}", file=sys.stderr)
        return True, ""

    try:
        output = run_command(
            prompt, project_path,
            allowed_tools=["Read", "Glob", "Grep"],
            model_key="lightweight",
            max_turns=3,
            timeout=120,
            max_turns_source=None,
        )
    except Exception as e:
        print(f"[plan_runner] Review subagent failed: {e} — skipping review", file=sys.stderr)
        return True, ""

    if not output:
        return True, ""

    first_line = output.strip().splitlines()[0].strip() if output.strip() else ""

    if first_line.upper().startswith("APPROVED"):
        return True, ""

    if first_line.upper().startswith("ISSUES_FOUND"):
        # Everything after the first line is the list of issues
        rest = "\n".join(output.strip().splitlines()[1:]).strip()
        return False, rest

    # Malformed reviewer output — fail open rather than block
    print(
        f"[plan_runner] Review returned unexpected output (treating as approved): "
        f"{first_line!r}",
        file=sys.stderr,
    )
    return True, ""


def improve_plan(
    plan_text: str, issues_text: str, project_path: str, skill_dir
) -> str:
    """Run a codebase-grounded subagent to fix plan quality issues.

    The improver explores the codebase to resolve ambiguities identified by
    the reviewer (missing file paths, vague descriptions, etc.) and returns
    a corrected plan.

    Args:
        plan_text: The plan that failed review.
        issues_text: Bullet list of issues from the reviewer.
        project_path: Project directory (for codebase exploration).
        skill_dir: Skill directory for loading the improve prompt.

    Returns:
        Improved plan text, or original plan_text on failure.
    """
    from app.cli_provider import run_command

    try:
        prompt = load_prompt_or_skill(
            skill_dir, "plan-improve", PLAN=plan_text, ISSUES=issues_text
        )
    except Exception as e:
        print(f"[plan_runner] Improve prompt load failed: {e}", file=sys.stderr)
        return plan_text

    try:
        output = run_command(
            prompt, project_path,
            allowed_tools=["Read", "Glob", "Grep"],
            model_key="chat",
            max_turns=5,
            timeout=180,
            max_turns_source=None,
        )
    except Exception as e:
        print(f"[plan_runner] Improve subagent failed: {e}", file=sys.stderr)
        return plan_text

    if not output or not output.strip():
        print("[plan_runner] Improve subagent returned empty — keeping original", file=sys.stderr)
        return plan_text

    return output.strip()


def _review_loop(
    plan_text: str,
    project_path: str,
    idea: str,
    context: str,
    skill_dir,
    max_rounds: int = 3,
    is_iteration: bool = False,
    issue_context: str = "",
) -> str:
    """Iteratively review and re-generate a plan until approved or rounds exhausted.

    Args:
        plan_text: Initial plan text to review.
        project_path: Project directory.
        idea: Original idea string (for new plans).
        context: User context string (for new plans).
        skill_dir: Skill directory.
        max_rounds: Maximum review+regen cycles.
        is_iteration: If True, re-generate using plan-iterate prompt.
        issue_context: Issue context string (for iteration plans).

    Returns:
        Final plan text (best version after review loop).
    """
    current_plan = plan_text
    prev_issues: Optional[str] = None
    final_round = 0

    for round_num in range(1, max_rounds + 1):
        approved, issues = review_plan(current_plan, project_path, skill_dir)
        final_round = round_num

        if approved:
            print(f"[plan_runner] Review round {round_num}: APPROVED", file=sys.stderr)
            _record_plan_metric(project_path, True, round_num, "")
            return current_plan

        print(f"[plan_runner] Review round {round_num}: ISSUES_FOUND", file=sys.stderr)
        if issues:
            print(f"[plan_runner] Issues:\n{issues}", file=sys.stderr)

        if round_num == max_rounds:
            print(
                f"[plan_runner] Max review rounds ({max_rounds}) exhausted — "
                "posting best version with warning",
                file=sys.stderr,
            )
            _record_plan_metric(project_path, False, round_num, issues or "")
            return current_plan + _review_warning_note(issues, max_rounds)

        # Note if the same issues recur
        if prev_issues and prev_issues == issues:
            print(
                "[plan_runner] Same issues persisted from previous round — "
                "regenerating with stronger context",
                file=sys.stderr,
            )
        prev_issues = issues

        # Re-generate with reviewer feedback appended
        feedback_context = (context or "") + f"\n\n## Review Feedback\n\n{issues}"
        try:
            from app.skill_memory import build_memory_block_for_skill
            if is_iteration:
                project_memory = build_memory_block_for_skill(project_path, issue_context)
                new_plan = _run_claude_plan(
                    load_prompt_or_skill(
                        skill_dir, "plan-iterate",
                        ISSUE_CONTEXT=issue_context + f"\n\n## Review Feedback\n\n{issues}",
                        PROJECT_MEMORY=project_memory,
                    ),
                    project_path,
                )
            else:
                project_memory = build_memory_block_for_skill(project_path, idea)
                new_plan = _run_claude_plan(
                    load_prompt_or_skill(
                        skill_dir, "plan", IDEA=idea, CONTEXT=feedback_context,
                        PROJECT_MEMORY=project_memory,
                    ),
                    project_path,
                )
        except Exception as e:
            print(f"[plan_runner] Re-generation failed: {e} — keeping previous plan", file=sys.stderr)
            _record_plan_metric(project_path, False, final_round, "re-generation failed")
            return current_plan

        if new_plan:
            current_plan = new_plan
        else:
            print("[plan_runner] Re-generation returned empty — keeping previous plan", file=sys.stderr)

    _record_plan_metric(project_path, False, final_round, "loop exhausted")
    return current_plan


def _record_plan_metric(
    project_path: str,
    approved: bool,
    rounds: int,
    issues_summary: str,
) -> None:
    """Record a plan-review metric (fire-and-forget)."""
    try:
        import os
        instance_dir = os.path.join(os.environ.get("KOAN_ROOT", ""), "instance")
        project_name = Path(project_path).name
        from app.skill_metrics import record_plan_metric
        record_plan_metric(instance_dir, project_name, approved, rounds, issues_summary)
    except Exception as e:
        print(f"[plan_runner] Failed to record plan metric: {e}", file=sys.stderr)


def _review_warning_note(issues: str, max_rounds: int) -> str:
    """Build the warning note appended to a plan when review rounds are exhausted."""
    return (
        f"\n\n> ⚠️ Plan review flagged unresolved items after {max_rounds} rounds "
        f"— human review recommended.\n>\n"
        + "\n".join(f"> - {line.removeprefix('- ')}" for line in issues.splitlines() if line.strip())
    )


def _generate_plan(project_path, idea, context="", skill_dir=None):
    """Run Claude to generate a structured plan for a new idea."""
    from app.config import get_plan_review_config
    from app.skill_memory import build_memory_block_for_skill

    project_memory = build_memory_block_for_skill(project_path, idea)
    prompt = load_prompt_or_skill(
        skill_dir, "plan", IDEA=idea, CONTEXT=context, PROJECT_MEMORY=project_memory,
    )
    plan = _run_claude_plan(prompt, project_path)

    review_cfg = get_plan_review_config()
    if review_cfg["enabled"] and not is_simple_plan(plan):
        plan = _review_loop(
            plan, project_path, idea=idea, context=context, skill_dir=skill_dir,
            max_rounds=review_cfg["max_rounds"],
        )

    return plan


def _generate_iteration_plan(project_path, issue_context, skill_dir=None):
    """Run Claude to generate an updated plan based on issue + comments."""
    from app.config import get_plan_review_config
    from app.skill_memory import build_memory_block_for_skill

    project_memory = build_memory_block_for_skill(project_path, issue_context)
    prompt = load_prompt_or_skill(
        skill_dir, "plan-iterate",
        ISSUE_CONTEXT=issue_context,
        PROJECT_MEMORY=project_memory,
    )
    plan = _run_claude_plan(prompt, project_path)

    review_cfg = get_plan_review_config()
    if review_cfg["enabled"] and not is_simple_plan(plan):
        plan = _review_loop(
            plan, project_path, idea="", context="", skill_dir=skill_dir,
            max_rounds=review_cfg["max_rounds"],
            is_iteration=True, issue_context=issue_context,
        )

    return plan


# Regex matching preamble transition lines — everything up to and including
# such a line is stripped from the CLI output so it doesn't pollute the
# GitHub issue body.
_PREAMBLE_RE = re.compile(
    r"(?:now I have (?:all )?the context|"
    r"let me create the (?:comprehensive |structured )?plan|"
    r"here(?:'s| is) the (?:comprehensive |structured |implementation )?plan|"
    r"I'll create the plan|"
    r"let me (?:now )?(?:generate|write|draft|produce) the plan)",
    re.IGNORECASE,
)


def _strip_preamble(output: str) -> str:
    """Strip CLI exploration noise from the beginning of plan output.

    Some CLI providers (notably Copilot) include tool-call output and
    thinking text before the actual plan content. This function finds the
    last preamble transition line and returns only the plan that follows.
    """
    if not output:
        return output

    lines = output.splitlines()

    # Find the last line that matches a known preamble pattern.
    # Everything up to and including that line is noise.
    last_preamble_idx = -1
    for i, line in enumerate(lines):
        if _PREAMBLE_RE.search(line):
            last_preamble_idx = i

    if last_preamble_idx >= 0:
        remaining = "\n".join(lines[last_preamble_idx + 1:]).strip()
        if remaining:
            return remaining

    return output


def _is_error_output(output: str) -> bool:
    """Detect CLI error patterns in output that should not be posted as a plan."""
    if not output:
        return False
    # Claude CLI emits this when --max-turns is exhausted
    if "Reached max turns" in output:
        return True
    # Other known error patterns
    if output.lstrip().startswith("Error:") and len(output) < 200:
        return True
    return False


def _run_claude_plan(prompt, project_path):
    """Execute Claude CLI with the given prompt and return the output."""
    from app.cli_provider import run_command_streaming
    from app.config import get_skill_max_turns, get_skill_timeout
    output = run_command_streaming(
        prompt, project_path,
        allowed_tools=["Read", "Glob", "Grep", "WebFetch"],
        max_turns=get_skill_max_turns(), timeout=get_skill_timeout(),
    )
    if _is_error_output(output):
        raise RuntimeError(output)
    return _strip_preamble(output)






def _format_comments(comments):
    """Format comments list into readable text with authorship.

    Args:
        comments: List of dicts with keys: author, date, body.
    """
    if not isinstance(comments, list) or not comments:
        return ""

    parts = []
    for c in comments:
        author = c.get("author", "unknown")
        date = c.get("date", "")[:10]
        body = c.get("body", "").strip()
        if body:
            parts.append(f"**{author}** ({date}):\n{body}")
    return "\n\n---\n\n".join(parts)



def _extract_title(plan_text):
    """Extract the title from the first non-empty line of the plan.

    The plan prompt instructs Claude to write a short, descriptive title
    as the very first line (no # prefix). This function extracts that line,
    stripping any accidental markdown formatting or CLI noise characters.
    """
    lines = plan_text.strip().splitlines()
    for line in lines:
        line = line.strip()
        if not line:
            continue
        # Strip any markdown heading prefix the model may have added
        clean = re.sub(r'^#+\s*', '', line).strip()
        # Strip CLI noise characters (bullets, arrows, decorative prefixes)
        clean = re.sub(r'^[●•►▸▹▶◆◇○◎▪▫→⟶»>]+\s*', '', clean).strip()
        # Skip generic section headings that aren't real titles
        if clean.lower() in (
            "summary", "implementation plan", "plan",
            "open questions", "implementation steps",
            "implementation phases",
        ):
            continue
        if clean:
            return clean[:120]
    return "Implementation Plan"


def _strip_title_line(plan_text):
    """Remove the first non-empty line (title) from the plan text.

    The title is used as the GitHub issue title, so we strip it from the
    body to avoid duplication.
    """
    lines = plan_text.strip().splitlines()
    # Find and skip the first non-empty line
    for i, line in enumerate(lines):
        if line.strip():
            remaining = "\n".join(lines[i + 1:]).strip()
            return remaining if remaining else plan_text
    return plan_text


def _extract_idea_from_issue(body):
    """Extract the core idea from an issue body for re-planning."""
    if not body:
        return "Review and update this plan"
    lines = body.strip().splitlines()
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.startswith("---") or line.startswith("*Generated by"):
            continue
        clean = re.sub(r'^#+\s*', '', line).strip()
        clean = re.sub(r'^Plan:\s*', '', clean).strip()
        if clean and len(clean) > 3:
            return clean[:500]
    return "Review and refine this plan based on the discussion"


# ---------------------------------------------------------------------------
# CLI entry point -- python3 -m app.plan_runner
# ---------------------------------------------------------------------------

def main(argv=None):
    """CLI entry point for plan_runner.

    Returns exit code (0 = success, 1 = failure).
    """
    import argparse
    import sys

    parser = argparse.ArgumentParser(
        description="Generate a structured plan and post as GitHub issue/comment."
    )
    parser.add_argument(
        "--project-path", required=True,
        help="Local path to the project repository",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--idea",
        help="New idea to plan",
    )
    group.add_argument(
        "--issue-url",
        help="GitHub issue URL to iterate on",
    )
    parser.add_argument(
        "--context",
        help="Additional user context (e.g. 'Focus on phase 2')",
    )
    cli_args = parser.parse_args(argv)

    skill_dir = Path(__file__).resolve().parent.parent / "skills" / "core" / "plan"

    success, summary = run_plan(
        project_path=cli_args.project_path,
        idea=cli_args.idea,
        issue_url=cli_args.issue_url,
        skill_dir=skill_dir,
        context=cli_args.context,
    )
    print(summary)
    return 0 if success else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
