"""Tests for app.pr_footer — shared Kōan footer helpers."""

import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
os.environ.setdefault("KOAN_ROOT", "/tmp/test-koan")

from app.pr_footer import build_koan_footer, strip_legacy_footers, KOAN_URL


class TestBuildKoanFooter:
    def test_default(self):
        result = build_koan_footer()
        assert result == f"_Generated by [Kōan]({KOAN_URL})_"

    def test_custom_action(self):
        result = build_koan_footer(action="Automated review by")
        assert result == f"_Automated review by [Kōan]({KOAN_URL})_"

    def test_provider_only(self):
        result = build_koan_footer(provider_name="claude")
        assert "Claude" in result
        assert f"[Kōan]({KOAN_URL})" in result
        assert "_(Claude)_" in result

    def test_model_only(self):
        result = build_koan_footer(model="opus-4-6")
        assert "model opus-4-6" in result
        assert f"[Kōan]({KOAN_URL})" in result

    def test_provider_and_model(self):
        result = build_koan_footer(provider_name="claude", model="opus-4-6")
        assert "_(Claude · model opus-4-6)_" in result
        assert f"[Kōan]({KOAN_URL})" in result

    def test_provider_capitalized(self):
        result = build_koan_footer(provider_name="copilot")
        assert "Copilot" in result

    def test_review_footer_compat(self):
        result = build_koan_footer(
            action="Automated review by",
            provider_name="claude",
            model="opus-4-6",
        )
        expected = (
            f"_Automated review by [Kōan]({KOAN_URL})_"
            " _(Claude · model opus-4-6)_"
        )
        assert result == expected


class TestStripLegacyFooters:
    def test_strip_star_footer(self):
        body = "## Summary\n\nChanges.\n\n*Generated by Kōan /fix*"
        result = strip_legacy_footers(body)
        assert "Generated by" not in result
        assert "Changes." in result

    def test_strip_italic_footer(self):
        body = "## Summary\n\nChanges.\n\n_Generated by Kōan `/claudemd`_"
        result = strip_legacy_footers(body)
        assert "Generated by" not in result

    def test_strip_claude_code_footer(self):
        body = "## Summary\n\nChanges.\n\n🤖 Generated with [Claude Code](https://claude.ai/code)"
        result = strip_legacy_footers(body)
        assert "Claude Code" not in result
        assert "Changes." in result

    def test_strip_claude_code_plain(self):
        body = "## Summary\n\nChanges.\n\n🤖 Generated with Claude Code"
        result = strip_legacy_footers(body)
        assert "Claude Code" not in result

    def test_strip_review_footer(self):
        body = "## Review\n\nFindings.\n\n_Automated review by Kōan_"
        result = strip_legacy_footers(body)
        assert "Automated review" not in result

    def test_strip_review_footer_with_link(self):
        body = f"## Review\n\n_Automated review by [Kōan]({KOAN_URL})_ _(Claude · model opus-4-6)_"
        result = strip_legacy_footers(body)
        assert "Automated review" not in result

    def test_strip_branded_footer(self):
        body = f"## Summary\n\nChanges.\n\n---\n_Generated by [Kōan]({KOAN_URL})_"
        result = strip_legacy_footers(body)
        assert "Generated by" not in result
        assert "---" not in result

    def test_strip_branded_footer_with_provider(self):
        body = (
            "## Summary\n\nChanges.\n\n---\n"
            f"_Generated by [Kōan]({KOAN_URL})_ _(Claude · model opus-4-6)_"
        )
        result = strip_legacy_footers(body)
        assert "Generated by" not in result

    def test_strip_multiple_footers(self):
        body = (
            "## Summary\n\nChanges.\n\n"
            "🤖 Generated with [Claude Code](https://claude.ai/code)\n\n"
            "---\n*Generated by Kōan post-mission quality pipeline*"
        )
        result = strip_legacy_footers(body)
        assert "Claude Code" not in result
        assert "Generated by" not in result
        assert "Changes." in result

    def test_strip_koan_without_accent(self):
        body = "## Summary\n\n*Generated by Koan /fix*"
        result = strip_legacy_footers(body)
        assert "Generated by" not in result

    def test_preserves_regular_content(self):
        body = "## Summary\n\nGenerated excellent results.\n\nNo footer here."
        result = strip_legacy_footers(body)
        assert result == body

    def test_collapses_trailing_separator(self):
        body = "## Summary\n\nChanges.\n\n---\n*Generated by Kōan*"
        result = strip_legacy_footers(body)
        assert result.endswith("Changes.")
        assert "---" not in result

    def test_empty_body(self):
        assert strip_legacy_footers("") == ""
